### ISSUE TITLE
Add nodejs 4.x support

### ISSUE THREAD

**Issue by Semigradsky** [jonathantneal/postcss-pseudo-class-any-link#7]
Nodejs 4.x will be maintained [until 2018-04-01](https://github.com/nodejs/LTS#lts-schedule1), but this package supports only nodejs 6.9.1+

**Comment by jonathantneal** [comment]
Resolved in via https://github.com/jonathantneal/postcss-pseudo-class-any-link/commit/877bfc48f6b7ab46f76cc8dd92476585f6ee6287

Now supporting PostCSS v6, Node 4x
